### ISSUE TITLE
Configure - Hosting

### ISSUE THREAD

**Issue by ClearlyElevated** [DeathHound6/TotalBan#9]
Going to deploy it now. Ill add you to the project so you can configure your details

**Comment by DeathHound6** [comment]
I’ve been recommend to get a raspi for self hosting. What’s your thoughts on it?

**Comment by ClearlyElevated** [comment]
> I've got the whole bot and site onto one glitch project now if we wanna try remix?

Yup. **Link me**

**Comment by ClearlyElevated** [comment]
You should also add a git ignore. I can help u if u want. It would prevent all the stupid extra glitch files from me pushed

**Comment by DeathHound6** [comment]
Found a hosting server that runs well
